apiVersion: v1
kind: Service
metadata:
  name: inventory-microservice
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
  selector:
    app: inventory-microservice
