apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-microservice
  template:
    metadata:
      labels:
        app: inventory-microservice
    spec:
      containers:
      - name: inventory-microservice
        image: rishiwhite11/inventory:1.0.9
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: order-microservice-config
