apiVersion: v1
kind: Secret
metadata:
  name: pgsql-secret
type: Opaque
data:
  username: ZHJhZ3Vub3Y=  # base64 encoded value of 'dragunov'
  password: ZHJhZ3Vub3Y=  # base64 encoded value of 'dragunov'
  database: ZHJhZ3Vub3Y=  # base64 encoded value of 'dragunov'
