apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-microservice
  template:
    metadata:
      labels:
        app: order-microservice
    spec:
      containers:
      - name: order-microservice
        image: rishiwhite11/orders:1.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: ENVIRONMENT
          value: "KUBERNETES"
        envFrom:
        - configMapRef:
            name: order-microservice-config
