apiVersion: v1
kind: Service
metadata:
  name: notifications-microservice
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30002
  selector:
    app: notifications-microservice
