apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-microservice
  template:
    metadata:
      labels:
        app: notifications-microservice
    spec:
      containers:
      - name: notifications-microservice
        image: rishiwhite11/notification:1.0.11
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: order-microservice-config
